// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("AlembicVersions", testAlembicVersions)
	t.Run("OrganizationMembers", testOrganizationMembers)
	t.Run("Organizations", testOrganizations)
	t.Run("Projects", testProjects)
	t.Run("Sboms", testSboms)
	t.Run("Users", testUsers)
	t.Run("Vulnerabilities", testVulnerabilities)
}

func TestDelete(t *testing.T) {
	t.Run("AlembicVersions", testAlembicVersionsDelete)
	t.Run("OrganizationMembers", testOrganizationMembersDelete)
	t.Run("Organizations", testOrganizationsDelete)
	t.Run("Projects", testProjectsDelete)
	t.Run("Sboms", testSbomsDelete)
	t.Run("Users", testUsersDelete)
	t.Run("Vulnerabilities", testVulnerabilitiesDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("AlembicVersions", testAlembicVersionsQueryDeleteAll)
	t.Run("OrganizationMembers", testOrganizationMembersQueryDeleteAll)
	t.Run("Organizations", testOrganizationsQueryDeleteAll)
	t.Run("Projects", testProjectsQueryDeleteAll)
	t.Run("Sboms", testSbomsQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
	t.Run("Vulnerabilities", testVulnerabilitiesQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("AlembicVersions", testAlembicVersionsSliceDeleteAll)
	t.Run("OrganizationMembers", testOrganizationMembersSliceDeleteAll)
	t.Run("Organizations", testOrganizationsSliceDeleteAll)
	t.Run("Projects", testProjectsSliceDeleteAll)
	t.Run("Sboms", testSbomsSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
	t.Run("Vulnerabilities", testVulnerabilitiesSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("AlembicVersions", testAlembicVersionsExists)
	t.Run("OrganizationMembers", testOrganizationMembersExists)
	t.Run("Organizations", testOrganizationsExists)
	t.Run("Projects", testProjectsExists)
	t.Run("Sboms", testSbomsExists)
	t.Run("Users", testUsersExists)
	t.Run("Vulnerabilities", testVulnerabilitiesExists)
}

func TestFind(t *testing.T) {
	t.Run("AlembicVersions", testAlembicVersionsFind)
	t.Run("OrganizationMembers", testOrganizationMembersFind)
	t.Run("Organizations", testOrganizationsFind)
	t.Run("Projects", testProjectsFind)
	t.Run("Sboms", testSbomsFind)
	t.Run("Users", testUsersFind)
	t.Run("Vulnerabilities", testVulnerabilitiesFind)
}

func TestBind(t *testing.T) {
	t.Run("AlembicVersions", testAlembicVersionsBind)
	t.Run("OrganizationMembers", testOrganizationMembersBind)
	t.Run("Organizations", testOrganizationsBind)
	t.Run("Projects", testProjectsBind)
	t.Run("Sboms", testSbomsBind)
	t.Run("Users", testUsersBind)
	t.Run("Vulnerabilities", testVulnerabilitiesBind)
}

func TestOne(t *testing.T) {
	t.Run("AlembicVersions", testAlembicVersionsOne)
	t.Run("OrganizationMembers", testOrganizationMembersOne)
	t.Run("Organizations", testOrganizationsOne)
	t.Run("Projects", testProjectsOne)
	t.Run("Sboms", testSbomsOne)
	t.Run("Users", testUsersOne)
	t.Run("Vulnerabilities", testVulnerabilitiesOne)
}

func TestAll(t *testing.T) {
	t.Run("AlembicVersions", testAlembicVersionsAll)
	t.Run("OrganizationMembers", testOrganizationMembersAll)
	t.Run("Organizations", testOrganizationsAll)
	t.Run("Projects", testProjectsAll)
	t.Run("Sboms", testSbomsAll)
	t.Run("Users", testUsersAll)
	t.Run("Vulnerabilities", testVulnerabilitiesAll)
}

func TestCount(t *testing.T) {
	t.Run("AlembicVersions", testAlembicVersionsCount)
	t.Run("OrganizationMembers", testOrganizationMembersCount)
	t.Run("Organizations", testOrganizationsCount)
	t.Run("Projects", testProjectsCount)
	t.Run("Sboms", testSbomsCount)
	t.Run("Users", testUsersCount)
	t.Run("Vulnerabilities", testVulnerabilitiesCount)
}

func TestHooks(t *testing.T) {
	t.Run("AlembicVersions", testAlembicVersionsHooks)
	t.Run("OrganizationMembers", testOrganizationMembersHooks)
	t.Run("Organizations", testOrganizationsHooks)
	t.Run("Projects", testProjectsHooks)
	t.Run("Sboms", testSbomsHooks)
	t.Run("Users", testUsersHooks)
	t.Run("Vulnerabilities", testVulnerabilitiesHooks)
}

func TestInsert(t *testing.T) {
	t.Run("AlembicVersions", testAlembicVersionsInsert)
	t.Run("AlembicVersions", testAlembicVersionsInsertWhitelist)
	t.Run("OrganizationMembers", testOrganizationMembersInsert)
	t.Run("OrganizationMembers", testOrganizationMembersInsertWhitelist)
	t.Run("Organizations", testOrganizationsInsert)
	t.Run("Organizations", testOrganizationsInsertWhitelist)
	t.Run("Projects", testProjectsInsert)
	t.Run("Projects", testProjectsInsertWhitelist)
	t.Run("Sboms", testSbomsInsert)
	t.Run("Sboms", testSbomsInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
	t.Run("Vulnerabilities", testVulnerabilitiesInsert)
	t.Run("Vulnerabilities", testVulnerabilitiesInsertWhitelist)
}

func TestReload(t *testing.T) {
	t.Run("AlembicVersions", testAlembicVersionsReload)
	t.Run("OrganizationMembers", testOrganizationMembersReload)
	t.Run("Organizations", testOrganizationsReload)
	t.Run("Projects", testProjectsReload)
	t.Run("Sboms", testSbomsReload)
	t.Run("Users", testUsersReload)
	t.Run("Vulnerabilities", testVulnerabilitiesReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("AlembicVersions", testAlembicVersionsReloadAll)
	t.Run("OrganizationMembers", testOrganizationMembersReloadAll)
	t.Run("Organizations", testOrganizationsReloadAll)
	t.Run("Projects", testProjectsReloadAll)
	t.Run("Sboms", testSbomsReloadAll)
	t.Run("Users", testUsersReloadAll)
	t.Run("Vulnerabilities", testVulnerabilitiesReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("AlembicVersions", testAlembicVersionsSelect)
	t.Run("OrganizationMembers", testOrganizationMembersSelect)
	t.Run("Organizations", testOrganizationsSelect)
	t.Run("Projects", testProjectsSelect)
	t.Run("Sboms", testSbomsSelect)
	t.Run("Users", testUsersSelect)
	t.Run("Vulnerabilities", testVulnerabilitiesSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("AlembicVersions", testAlembicVersionsUpdate)
	t.Run("OrganizationMembers", testOrganizationMembersUpdate)
	t.Run("Organizations", testOrganizationsUpdate)
	t.Run("Projects", testProjectsUpdate)
	t.Run("Sboms", testSbomsUpdate)
	t.Run("Users", testUsersUpdate)
	t.Run("Vulnerabilities", testVulnerabilitiesUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("AlembicVersions", testAlembicVersionsSliceUpdateAll)
	t.Run("OrganizationMembers", testOrganizationMembersSliceUpdateAll)
	t.Run("Organizations", testOrganizationsSliceUpdateAll)
	t.Run("Projects", testProjectsSliceUpdateAll)
	t.Run("Sboms", testSbomsSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
	t.Run("Vulnerabilities", testVulnerabilitiesSliceUpdateAll)
}
