// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("OrganizationMemberToOrganizationUsingOrganization", testOrganizationMemberToOneOrganizationUsingOrganization)
	t.Run("OrganizationMemberToUserUsingUser", testOrganizationMemberToOneUserUsingUser)
	t.Run("ProjectToUserUsingCreatedByUser", testProjectToOneUserUsingCreatedByUser)
	t.Run("ProjectToOrganizationUsingOrganization", testProjectToOneOrganizationUsingOrganization)
	t.Run("ProjectToUserUsingOwner", testProjectToOneUserUsingOwner)
	t.Run("UserToOrganizationUsingOrganization", testUserToOneOrganizationUsingOrganization)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("OrganizationToOrganizationMembers", testOrganizationToManyOrganizationMembers)
	t.Run("OrganizationToProjects", testOrganizationToManyProjects)
	t.Run("OrganizationToUsers", testOrganizationToManyUsers)
	t.Run("UserToOrganizationMembers", testUserToManyOrganizationMembers)
	t.Run("UserToCreatedByProjects", testUserToManyCreatedByProjects)
	t.Run("UserToOwnerProjects", testUserToManyOwnerProjects)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("OrganizationMemberToOrganizationUsingOrganizationMembers", testOrganizationMemberToOneSetOpOrganizationUsingOrganization)
	t.Run("OrganizationMemberToUserUsingOrganizationMembers", testOrganizationMemberToOneSetOpUserUsingUser)
	t.Run("ProjectToUserUsingCreatedByProjects", testProjectToOneSetOpUserUsingCreatedByUser)
	t.Run("ProjectToOrganizationUsingProjects", testProjectToOneSetOpOrganizationUsingOrganization)
	t.Run("ProjectToUserUsingOwnerProjects", testProjectToOneSetOpUserUsingOwner)
	t.Run("UserToOrganizationUsingUsers", testUserToOneSetOpOrganizationUsingOrganization)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {
	t.Run("OrganizationMemberToOrganizationUsingOrganizationMembers", testOrganizationMemberToOneRemoveOpOrganizationUsingOrganization)
	t.Run("OrganizationMemberToUserUsingOrganizationMembers", testOrganizationMemberToOneRemoveOpUserUsingUser)
	t.Run("ProjectToUserUsingCreatedByProjects", testProjectToOneRemoveOpUserUsingCreatedByUser)
	t.Run("ProjectToOrganizationUsingProjects", testProjectToOneRemoveOpOrganizationUsingOrganization)
	t.Run("ProjectToUserUsingOwnerProjects", testProjectToOneRemoveOpUserUsingOwner)
	t.Run("UserToOrganizationUsingUsers", testUserToOneRemoveOpOrganizationUsingOrganization)
}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("OrganizationToOrganizationMembers", testOrganizationToManyAddOpOrganizationMembers)
	t.Run("OrganizationToProjects", testOrganizationToManyAddOpProjects)
	t.Run("OrganizationToUsers", testOrganizationToManyAddOpUsers)
	t.Run("UserToOrganizationMembers", testUserToManyAddOpOrganizationMembers)
	t.Run("UserToCreatedByProjects", testUserToManyAddOpCreatedByProjects)
	t.Run("UserToOwnerProjects", testUserToManyAddOpOwnerProjects)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("OrganizationToOrganizationMembers", testOrganizationToManySetOpOrganizationMembers)
	t.Run("OrganizationToProjects", testOrganizationToManySetOpProjects)
	t.Run("OrganizationToUsers", testOrganizationToManySetOpUsers)
	t.Run("UserToOrganizationMembers", testUserToManySetOpOrganizationMembers)
	t.Run("UserToCreatedByProjects", testUserToManySetOpCreatedByProjects)
	t.Run("UserToOwnerProjects", testUserToManySetOpOwnerProjects)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("OrganizationToOrganizationMembers", testOrganizationToManyRemoveOpOrganizationMembers)
	t.Run("OrganizationToProjects", testOrganizationToManyRemoveOpProjects)
	t.Run("OrganizationToUsers", testOrganizationToManyRemoveOpUsers)
	t.Run("UserToOrganizationMembers", testUserToManyRemoveOpOrganizationMembers)
	t.Run("UserToCreatedByProjects", testUserToManyRemoveOpCreatedByProjects)
	t.Run("UserToOwnerProjects", testUserToManyRemoveOpOwnerProjects)
}
